name: Build and deploy Node.js app to Azure Web App - tech0-gen8-step4-pos-app-111

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Verify .next directory exists
      - name: Verify build output directory
        run: |
          if [ -d ".next" ]; then
            echo ".next directory exists"
          else
            echo ".next directory does not exist"
            exit 1
          fi

      # Create deploy directory and copy build files
      - name: Create deploy directory and copy build files
        run: |
          mkdir -p ./deploy
          cp -r .next/* ./deploy/  # .next ディレクトリの内容を deploy ディレクトリにコピー

      - name: Check if deploy directory exists and has files
        run: |
          if [ -d "./deploy" ]; then
            echo "./deploy exists"
            ls ./deploy
          else
            echo "./deploy does not exist"
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          if [ -d "./deploy" ] && [ "$(ls -A ./deploy)" ]; then
            zip -r release.zip ./deploy/
          else
            echo "./deploy directory is empty or does not exist"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-111'
          slot-name: 'Production'
          package: ./deploy  # 展開されたディレクトリのパスを指定
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4BB0F180A54F4E75A3443D169FB0A8A6 }}
